[MOD]
Title=Sunrise
Author=Народ и его команда
AuthorEmail=ei-addon-dev@yandex.ru
URL=.
Date_DMY=13.03.2026
Version=0.0.0
Single=1
Multi=0
GameSaves=1
EnableNonlinearBrief=1
[CONFIG]
ai.reg=data\ai.reg
music.reg=sound\music.reg
movie.ini=movies\movie.ini
[RES]
sfx.res=sound\sfx.res
speech.res=sound\speech.res
figures.res=figures\figures_common.res
textures.res=textures\textures_common.res
textures.res=textures\interface.res
database.res=data\adb.res
database.res=data\database.res
texts.res=data\map_txt.res
texts.res=text\texts_common.res
texts.res=text\texts_prototypes.res
texts.res=text\texts_items.res
texts.res=text\texts_briefings.res
texts.res=text\texts_version.res
outro.res=text\texts_version.res
redress.res=textures\redress_human_male.res

;[Dev]
;plugin=plugin.dll